# Generated by Django 4.0.4 on 2022-05-08 13:29

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Category title')),
                ('slug', models.SlugField(verbose_name='Category Slug')),
                ('in_navbar', models.BooleanField(verbose_name='Category appears in navbar')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Document name')),
                ('file', models.FileField(upload_to=None, verbose_name='Document file')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Image name')),
                ('image', models.ImageField(upload_to=None, verbose_name='Image file')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Page title')),
                ('slug', models.SlugField(verbose_name='Page Slug')),
                ('content', django_quill.fields.QuillField(verbose_name="Quill's Richt Text")),
                ('in_navbar', models.BooleanField(verbose_name='Site appears in navbar')),
                ('type', models.CharField(choices=[('1', 'standard'), ('2', 'galary')], max_length=50, verbose_name='Page Types')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Page created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Page updated at')),
            ],
        ),
    ]
